name: victory_royale
description: Victory Royale - Tournament App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Firestore
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Ads
  google_mobile_ads: ^5.3.1

  # UI Polish Tools
  google_fonts: ^6.1.0        # Stylish fonts
  animations: ^2.0.11         # Page transitions, fade, slide, scale, etc.
  flutter_gradient_colors: ^2.1.1  # Gradient backgrounds
  flutter_svg: ^2.0.10        # For SVG icons (e.g., vector logos)
  shimmer: ^3.0.0             # Loading shimmer effect
  lottie: ^3.1.0              # For Lottie animation (e.g., loading, empty state)

  # Cupertino Icons (iOS style icons)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
