name: victory_royale
description: Victory Royale - Tournament App
publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Firestore
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Ads
  google_mobile_ads: ^5.3.1

  # UI & Effects
  google_fonts: ^6.1.0
  animations: ^2.0.11
  flutter_gradient_colors: ^2.1.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # iOS icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Recommended to downgrade to match Dart SDK

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
