workflows:
  build_apk:
    name: Build APK
    instance_type: mac_mini
    max_build_duration: 15
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          cd my_app
          flutter pub get
      - name: Build release APK
        script: |
          cd my_app
          flutter build apk --release
    artifacts:
      - my_app/build/app/outputs/flutter-apk/app-release.apk
