// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUiOVLqEWPmeS1cN70RCHqyo_FHjZHMpE',
    appId: '1:175309117868:web:49e70f5c6176042ddd8209',
    messagingSenderId: '175309117868',
    projectId: 'money-pooja',
    authDomain: 'money-pooja.firebaseapp.com',
    storageBucket: 'money-pooja.firebasestorage.app',
    measurementId: 'G-FNE9SCQ513',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8Yhwai4RS-lgy5wFzVzv8QLzvJxgo-4',
    appId: '1:175309117868:android:1262832698094e6edd8209',
    messagingSenderId: '175309117868',
    projectId: 'money-pooja',
    storageBucket: 'money-pooja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOzLtW412yf7SMw-qZnRCYLe2g1-Ta4w',
    appId: '1:175309117868:ios:446e91ae4e732d2add8209',
    messagingSenderId: '175309117868',
    projectId: 'money-pooja',
    storageBucket: 'money-pooja.firebasestorage.app',
    iosClientId: '175309117868-rk28040n082gjf0iv9hi67seiod2mefd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmOzLtW412yf7SMw-qZnRCYLe2g1-Ta4w',
    appId: '1:175309117868:ios:446e91ae4e732d2add8209',
    messagingSenderId: '175309117868',
    projectId: 'money-pooja',
    storageBucket: 'money-pooja.firebasestorage.app',
    iosClientId: '175309117868-rk28040n082gjf0iv9hi67seiod2mefd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUiOVLqEWPmeS1cN70RCHqyo_FHjZHMpE',
    appId: '1:175309117868:web:cda365b600e5327ddd8209',
    messagingSenderId: '175309117868',
    projectId: 'money-pooja',
    authDomain: 'money-pooja.firebaseapp.com',
    storageBucket: 'money-pooja.firebasestorage.app',
    measurementId: 'G-VPTMVNTHY1',
  );
}
